### ISSUE TITLE
E/flutter (32321): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method sampleImage on channel plugins.lykhonis.com/image_crop)

### ISSUE THREAD

**Issue by Flutter-Stack** [lijungegea/flutter_simple_image_crop#25]
E/flutter (32321): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method sampleImage on channel plugins.lykhonis.com/image_crop)
E/flutter (32321): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:7)
E/flutter (32321): <asynchronous suspension>
E/flutter (32321): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:334:12)
E/flutter (32321): #2      ImageCrop.sampleImage (package:simple_image_crop/src/simpleImageCrop.dart:79:40)
E/flutter (32321): #3      ImgCropState.cropCompleted (package:simple_image_crop/src/simpleCrop.dart:151:40)
E/flutter (32321): #4      _SimpleCropRouteState.build.<anonymous closure> (package:simple_crop/main.dart:151:28)
E/flutter (32321): #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:992:19)
E/flutter (32321): #6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1098:38)
E/flutter (32321): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:184:24)
E/flutter (32321): #8      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:524:11)
E/flutter (32321): #9      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:284:5)
E/flutter (32321): #10     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:256:7)
E/flutter (32321): #11     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:158:27)
E/flutter (32321): #12     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:224:20)
E/flutter (32321): #13     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:200:22)
E/flutter (32321): #14     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:158:7)
E/flutter (32321): #15     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:104:7)
E/flutter (32321): #16     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:88:7)
E/flutter (32321): #17     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter (32321): #18     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (32321): #19     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (32321): #20     _invoke1 (dart:ui/hooks.dart:267:10)
E/flutter (32321): #21     _dispatchPointerDataPacket (dart:ui/hooks.dart:176:5)
E/flutter (32321):

**Comment by Ali-Assi-1994** [comment]
Do we have any new updates for this issue?
I have the same here!

**Comment by lucas-livingnet** [comment]
I have the same here!

**Comment by hoangcuongdev** [comment]
This issue has been fixed by Migrating to AndroidX

**Comment by caoyanglee** [comment]
I have the same here!
